# Justfile for building and running a Zig project
alias r   := run
alias rw  := run-watch
alias brw := build-run-watch
alias br  := build-run
alias c   := clean

# Default target: build the project
[no-cd]
default:
    just run

# Simple run
[no-cd]
run:
    zig run main.zig

[no-cd]
run-watch:
    watchexec -e zig -r -c -- zig run main.zig

# Build the project using Zig
[no-cd]
build:
    zig build

# Run the project after building
[no-cd]
build-run *args:
    zig build run -- {{args}}

[no-cd]
build-run-watch:
    watchexec -e zig -r -c -- zig build run

# Clean build artifacts
[no-cd]
clean:
    rm -rf zig-out /tmp/zig-cache-local

# Rebuild from scratch
[no-cd]
rebuild: clean build

up:
    devpod up .

down:
    devpod down .

up-clean:
    devpod up --recreate .

